project:
  type: website

website:
  title: "Birusod"
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: /
      - icon: github
        href: https://github.com/birusod
      - icon: twitter
        href: https://twitter.com/birusod
      - icon: linkedin
        href: https://www.linkedin.com/in/diallooumarou/
      - icon: envelope
        href: mailto:birusod@gmail.com
format:
  html:
    theme: vapor
    css: styles.css
    smooth-scroll: true
    

editor: visual

